#!/bin/bash

################################################################################
# generic local build script for epics-containers ioc repositories                   #
################################################################################

# pass rtems as first argument to build RTEMS on cross-compiler
TARGET_ARCHITECTURE=${1:-linux}

set -xe

THIS_DIR=$(realpath $(dirname ${0}))
cd ${THIS_DIR}

# build runtime and developer images
ec dev build --arch ${TARGET_ARCHITECTURE}

# get the schema file from the developer container and save it locally
ec dev launch tests/example-ibek-config --execute \
'ibek ioc generate-schema /epics/links/ibek/*.ibek.support.yaml' \
> ibek.ioc.schema.json

